---
- name: Install Openvpn
  hosts: VPN
  become: true
  roles:
    - role: install-openvpn
      action: 00-gather-facts
    - role: install-openvpn
      action: 00-install-openvpn
    - role: install-openvpn
      action: 01-configure-service
    - role: install-openvpn
      action: 02-reload-service
    - role: prepare-system
      action: 05-reboot-machines
