---
- name: If Python is not installed, install it
  hosts: VPN
  become: true
  gather_facts: no
  pre_tasks:
    - raw: test -e /bin/python3 || apt-get install python3 -y

- name: Prepare System
  hosts: VPN
  become: true
  roles:
    - role: prepare-system
      action: 00-update-system
    - role: prepare-system
      action: 01-install-software
    - role: prepare-system
      action: 02-configure-services
    - role: prepare-system
      action: 03-reload-services
    - role: prepare-system
      action: 04-make-ip-static
    #- role: prepare-system
    #  action: 05-reboot-machines