---
- name: Enable IPv4 forward without reboot
  ansible.builtin.shell: echo 1 > /proc/sys/net/ipv4/ip_forward

- name: Enable systemd iptables rules
  ansible.builtin.systemd:
    name: openvpn-iptables.service
    enabled: true
    state: restarted
    daemon_reload: true
  when: not enable_vpn_only_communication

- name: Restart OpenVPN Server
  ansible.builtin.systemd:
    name: openvpn-server@server.service
    enabled: true
    state: restarted
    daemon_reload: true
