---
- name: Check System
  ansible.builtin.fail:
    msg: Only Debian is supported by this Playbook
  when: ansible_distribution != 'Debian'

- name: Update System
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
