---
- name: Copy SSH config
  ansible.builtin.template:
    src: ssh.conf.j2
    dest: /etc/ssh/sshd_config.d/sshd.conf
    owner: root
    mode: 0644

- name: Set Hostname
  ansible.builtin.template:
    src: etc/hostname.j2
    dest: /etc/hostname
    owner: root
    mode: 0644
  when: network.hostname is defined and network.hostname | length > 0

- name: Allow SSH ufw
  community.general.ufw:
    rule: allow
    port: "{{ ssh_port }}"

- name: Allow VPN ufw
  community.general.ufw:
    rule: allow
    port: "{{ vpn.port }}"
