---
- name: Copy SSH config
  template:
    src: ssh.conf.j2
    dest: /etc/ssh/sshd_config.d/sshd.conf
    owner: root
    mode: 0644

- name: Set Hostname
  template:
    src: etc/hostname
    dest: /etc/hostname
    owner: root
    mode: 0644

- name: Allow SSH ufw
  community.general.ufw:
    rule: allow
    port: "{{ ssh_port }}"

- name: Allow VPN ufw
  community.general.ufw:
    rule: allow
    port: "{{ vpn.port }}"
