---
- name: Retrieve Interface Name
  shell: "ip -4 -f inet -br link | head -n2 | tail +2 | cut -f 1 -d \" \""
  register: interface_name

- name: Set Static IP
  template:
    src: etc/network/interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    mode: 0644
