---
- name: Reboot Machine
  reboot:
    reboot_timeout: 5
  ignore_errors: true

- name: Set new Machine IP locally
  set_fact:
    ansible_host: "{{ network.static_ip }}"

- name: Wait for Machine to be back Online
  pause:
    minutes: 2